#
# Copyright (c) 2012-2015 André Bargull
# Alle Rechte vorbehalten / All Rights Reserved.  Use is subject to license terms.
#
# <https://github.com/anba/es6draft>
#

language: java

sudo: false

env:
  global:
    - TEST262_PATH='~/test262'

matrix:
  include:
    # Run the default profile with Java 7-9 (latest through installer)
    - &Profile_SkipExternal
      addons: {apt: {packages: oracle-java7-installer}}
      env: PROFILE='skip-external'
    - <<: *Profile_SkipExternal
      addons: {apt: {packages: oracle-java8-installer}}
    - <<: *Profile_SkipExternal
      addons: {apt: {packages: oracle-java9-installer}}
    # Run test262 profile with Java 8-9
    - &Profile_Test262
      addons: {apt: {packages: oracle-java8-installer}}
      env: PROFILE='test262-travisci'
    - <<: *Profile_Test262
      addons: {apt: {packages: oracle-java9-installer}}

# before_install: <cmd>

install:
  - if [[ $PROFILE = 'test262-travisci' ]]; then git clone --depth 1 --branch master git://github.com/tc39/test262.git "${TEST262_PATH}"; else true; fi
  - mvn install --show-version --batch-mode --quiet --errors -DskipTests=true

# before_script: <cmd>

script: mvn verify --batch-mode --activate-profiles "${PROFILE}"

# after_script: <cmd>

# after_success: <cmd>

# after_failure: <cmd>

notifications:
  email:
    on_success: always
    on_failure: always
