#
# Copyright (c) 2012-2014 André Bargull
# Alle Rechte vorbehalten / All Rights Reserved.  Use is subject to license terms.
#
# <https://github.com/anba/es6draft>
#

language: java

jdk:
  - oraclejdk7
  - oraclejdk8

before_install:
  - if [[ $TRAVIS_JDK_VERSION = 'oraclejdk8' ]]; then sudo apt-get update; sudo apt-get install oracle-java8-installer; else true; fi

# install: <cmd>

# before_script: <cmd>

script: mvn verify -Pskip-external

# after_script: <cmd>

# after_success: <cmd>

# after_failure: <cmd>

notifications:
  email:
    on_success: always
    on_failure: always
