#
# Copyright (c) 2012-2015 André Bargull
# Alle Rechte vorbehalten / All Rights Reserved.  Use is subject to license terms.
#
# <https://github.com/anba/es6draft>
#

language: java

sudo: false

env:
  global:
    - TEST262_PATH='~/test262'

matrix:
  include:
    # Run the default profile with Java 7-9 (latest through installer)
    - addons: {apt: {packages: oracle-java7-installer}}
      jdk: oraclejdk7
      env: PROFILE='skip-external' JAVA_VERSION=7
    - addons: {apt: {packages: oracle-java8-installer}}
      jdk: oraclejdk8
      env: PROFILE='skip-external' JAVA_VERSION=8
    - addons: {apt: {packages: oracle-java9-installer}}
      # jdk: oraclejdk9
      env: PROFILE='skip-external' JAVA_VERSION=9
    # Run test262 profile with Java 8-9
    - addons: {apt: {packages: oracle-java8-installer}}
      jdk: oraclejdk8
      env: PROFILE='test262-travisci' JAVA_VERSION=8
    - addons: {apt: {packages: oracle-java9-installer}}
      # jdk: oraclejdk9
      env: PROFILE='test262-travisci' JAVA_VERSION=9

before_install:
  - remove_dir_from_path $JAVA_HOME/bin
  - export JAVA_HOME=/usr/lib/jvm/java-$JAVA_VERSION-oracle
  - export PATH=$JAVA_HOME/bin:$PATH
  - java -version
  - if [[ $JAVA_VERSION = '9' ]]; then echo "export MAVEN_OPTS='-Dmaven.repo.local=$HOME/.m2/repository -Xmx512m'" > ~/.mavenrc; else true; fi

install:
  - if [[ $PROFILE = 'test262-travisci' ]]; then git clone --depth 1 --branch master git://github.com/tc39/test262.git "${TEST262_PATH}"; else true; fi
  - mvn install --show-version --batch-mode --quiet --errors -DskipTests=true

# before_script: <cmd>

script: mvn verify --batch-mode --activate-profiles "${PROFILE}"

# after_script: <cmd>

# after_success: <cmd>

# after_failure: <cmd>

notifications:
  email:
    on_success: always
    on_failure: always
